from os.path import abspath, dirname, join

import numpy as np
import numpy.ma as ma

import bedmap2
import bedmap2.transform


def test_bedmap2_version() -> None:
    """
    Check the bedmap2 version.
    """
    assert bedmap2.__version__ == "0.0.1"


def test_values() -> None:
    """
    Compare the values generated by this package
    to values generated using a reference MATLAB implementation.
    """

    # the directory where the test data is stored
    data_dir = join(dirname(abspath(__file__)), "bedmap_test_values.csv")

    # load the test data and mask NaN values.
    data = ma.masked_invalid(np.loadtxt(data_dir, delimiter=","))

    # extract the latitude and longitude of the test data
    lat = data[:, 0]
    lon = data[:, 1]

    # get the x and y coordinates of the point and check
    x, y = bedmap2.transform.latlon_to_xy(lat, lon)

    # check that x and y match
    np.testing.assert_allclose(np.asarray(x, dtype=np.int), data[:, 2], rtol=0.6e-2)
    np.testing.assert_allclose(np.asarray(y, dtype=np.int), data[:, 3], rtol=0.6e-2)
